name: Publish New Release To Crates.io

on:
  release:
    types:
      # This used to be `published` but `released` makes sure not to run when a
      # `prerelease` version has been created.
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      - released

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # If something goes wrong and there's a breaking change don't publish
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
